# Generated By: Cursor (Claude Sonnet 4.5)
import time
import re
import os
from threading import Thread

filesWatched = []

DEBUG = False

def setDebug(value):
    global DEBUG
    DEBUG = value

def debug(message):
    if DEBUG == True:
        print(message)

def findNewestFile(directory, logfileregex):
    now=time.time()
    filemtimes = {}
    for root, _, files in os.walk(directory, topdown=False):
        for name in files:
            m = re.match(logfileregex, name)
            if m is not None:
                filename = os.path.join(root, name)
                mtime = os.path.getmtime(filename)
                if mtime >= now - 30*60:
                    # file was modified in the last 30 minutes.  consider it. else ignore it.
                    filemtimes[mtime] = filename
    s = sorted(filemtimes.items())
    if len(s) == 0:
        return None
    return s[-1][1]

def watchFile(filename, frequencySeconds, callback):
    try:
        if filename in filesWatched:
            print("Attempted create duplicate watchFile on: {}".format(filename))
            pass

        print("Creating watchFile on: {}".format(filename))

        filesWatched.append(filename)
        with open(filename, 'r') as f:
            while True:
                line = f.readline()
                if not line:
                    time.sleep(frequencySeconds)
                else:
                    callback(filename, line)
    except Exception as e:
        # print the error in case it helps debug and remove the file from being tracked
        print(e)
        if filename in filesWatched:
            filesWatched.remove(filename)
        pass

def watchDirectory(logdir, logfileregex, frequencySeconds, callback):
    while True:
        newestLogFile = findNewestFile(logdir, logfileregex)
        while newestLogFile is None or newestLogFile in filesWatched:
            time.sleep(frequencySeconds)
            newestLogFile = findNewestFile(logdir, logfileregex)

        # got a new log file, attempt to start watching it
        t = Thread(target=watchFile, args=(newestLogFile,frequencySeconds,callback), daemon=True)
        t.start()


